//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1240.0 using the following command:
// xscgen .\SubmitChapterIVData.xsd
namespace Be.Fgov.Ehealth.Samws.V2.Core
{
    
    
    /// <summary>
    /// <para>Type of environment in which a medicinal product is delivered.
    ///        Possible values :
    ///        - ‘P’ for Public,
    ///        - ‘A’ for Ambulatory,
    ///        - ‘H’ for Hospital,
    ///        - ‘R’ For Residential care</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Type of environment in which a medicinal product is delivered. Possible values : " +
        "- ‘P’ for Public, - ‘A’ for Ambulatory, - ‘H’ for Hospital, - ‘R’ For Residentia" +
        "l care"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeliveryEnvironmentType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum DeliveryEnvironmentType
    {
        
        P,
        
        A,
        
        H,
        
        R,
    }
    
    /// <summary>
    /// <para>Type of the mentioned code, among the following:
    ///        - ‘CNK’: Code National – Nationale Kode . This code is attributed by the APB (“Association Pharmaceutique
    ///        Belge”) to identify unequivocally one medicinal product package, or by the NIHDI for identifying tarification
    ///        units, which meet to the same reimbursement criteria.
    ///        - ‘PSEUDO’: Pseudo-code used for the flat-pricing of drugs in certain environments such as radiopharmaca in
    ///        hospitals.
    ///        - ‘PSEUDOCODE’: Code used for the flat-pricing of drugs in certain environments such as radiopharmaca in
    ///        hospitals.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Type of the mentioned code, among the following: - ‘CNK’: Code National – Nationale Kode . This code is attributed by the APB (“Association Pharmaceutique Belge”) to identify unequivocally one medicinal product package, or by the NIHDI for identifying tarification units, which meet to the same reimbursement criteria. - ‘PSEUDO’: Pseudo-code used for the flat-pricing of drugs in certain environments such as radiopharmaca in hospitals. - ‘PSEUDOCODE’: Code used for the flat-pricing of drugs in certain environments such as radiopharmaca in hospitals.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DmppCodeTypeType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum DmppCodeTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CNK")]
        Cnk,
        
        [System.Xml.Serialization.XmlEnumAttribute("PSEUDO")]
        Pseudo,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IngredientTypeType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum IngredientTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ACTIVE_SUBSTANCE")]
        ActiveSubstance,
        
        [System.Xml.Serialization.XmlEnumAttribute("EXCIPIENT")]
        Excipient,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VmpKeyType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VmpKeyType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("code")]
        public int Code { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VmpComponentKeyType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VmpComponentKeyType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("code")]
        public int Code { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AnomalyType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnomalyType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public string Code { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TargetObject")]
        public string TargetObject { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TargetReference")]
        public string TargetReference { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QuantityType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuantityType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum exclusive value: 10000000000000000.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RangeType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RangeType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum exclusive value: 10000000000000000.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Min")]
        public decimal Min { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Total number of digits: 20.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum exclusive value: 10000000000000000.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Max")]
        public decimal Max { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardResponseType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.AddNameExplanationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.AddParagraphResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.AddQualificationListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.RemoveNameExplanationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.RemoveParagraphResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Be.Fgov.Ehealth.Samws.V2.Chapteriv.Submit.RemoveQualificationListResponse))]
    public partial class StandardResponseType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AnomalyType> _anomaly;
        
        [System.Xml.Serialization.XmlElementAttribute("Anomaly")]
        public System.Collections.ObjectModel.Collection<AnomalyType> Anomaly
        {
            get
            {
                return _anomaly;
            }
            private set
            {
                _anomaly = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Anomaly collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnomalySpecified
        {
            get
            {
                return (this.Anomaly.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StandardResponseType" /> class.</para>
        /// </summary>
        public StandardResponseType()
        {
            this._anomaly = new System.Collections.ObjectModel.Collection<AnomalyType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StrengthRangeType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StrengthRangeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumeratorRange")]
        public RangeType NumeratorRange { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Denominator")]
        public QuantityType Denominator { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StrengthType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StrengthType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Numerator")]
        public QuantityType Numerator { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Denominator")]
        public QuantityType Denominator { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TextType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TextType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Fr")]
        public string Fr { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Nl")]
        public string Nl { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("De")]
        public string De { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("En")]
        public string En { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Text255Type", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Text255Type
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Fr")]
        public string Fr { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nl")]
        public string Nl { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.Xml.Serialization.XmlElementAttribute("De")]
        public string De { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: \S.*\S|\S.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S.*\\S|\\S")]
        [System.Xml.Serialization.XmlElementAttribute("En")]
        public string En { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("allActionsType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum AllActionsType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ADD")]
        Add,
        
        [System.Xml.Serialization.XmlEnumAttribute("CHANGE")]
        Change,
        
        [System.Xml.Serialization.XmlEnumAttribute("REMOVE")]
        Remove,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO_CHANGE")]
        NoChange,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("addChangeRemoveType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum AddChangeRemoveType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ADD")]
        Add,
        
        [System.Xml.Serialization.XmlEnumAttribute("CHANGE")]
        Change,
        
        [System.Xml.Serialization.XmlEnumAttribute("REMOVE")]
        Remove,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("addActionType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum AddActionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ADD")]
        Add,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("addNoChangeActionsType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum AddNoChangeActionsType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ADD")]
        Add,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO_CHANGE")]
        NoChange,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("changeActionType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum ChangeActionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CHANGE")]
        Change,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("changeNoChangeActionType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum ChangeNoChangeActionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CHANGE")]
        Change,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO_CHANGE")]
        NoChange,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("removeActionType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum RemoveActionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("REMOVE")]
        Remove,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("removeNoChangeActionsType", Namespace="urn:be:fgov:ehealth:samws:v2:core")]
    public enum RemoveNoChangeActionsType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("REMOVE")]
        Remove,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO_CHANGE")]
        NoChange,
    }
    
    /// <summary>
    /// <para>A default action period has a required from date and optional to date</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A default action period has a required from date and optional to date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    public partial interface IActionPeriod
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1830-10-04.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999-12-31.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1830-10-04", "9999-12-31")]
        System.DateTime From
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1830-10-04.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999-12-31.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1830-10-04", "9999-12-31")]
        System.DateTime To
        {
            get;
            set;
        }
    }
}
